# Generated by Django 5.2.5 on 2025-09-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('drap_admin', 'DRAP Admin'), ('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('warehouse', 'Warehouse'), ('wholesaler', 'Wholesaler'), ('shopkeeper', 'Shopkeeper'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
