# Generated by Django 5.2.5 on 2025-09-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('drap', 'DRAP Admin'), ('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('warehouse', 'Warehouse'), ('wholesaler', 'Wholesaler'), ('shopkeeper', 'Shopkeeper'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
    ]
