# Generated by Django 5.2.6 on 2025-12-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_customuser_is_approved_customuser_is_blacklisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_blacklisted',
        ),
    ]
