# Generated by Django 5.2.6 on 2025-12-28 20:47

import userauth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_remove_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', userauth.models.CustomUserManager()),
            ],
        ),
    ]
