"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6#r8cl9)z*iyn4u6$g*r8!zlx88z%lcz7@&pvmn17__8rz457f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    # "medicine.apps.MedicineConfig",
    'userauth',
    'django_extensions',
    'dashboard',
    "corsheaders",
    "blockchain",
    "medicine",

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pharmadb',
        'USER': 'postgres',
        'PASSWORD': 'kaplan001',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'userauth.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

APPEND_SLASH = True

CORS_ALLOW_CREDENTIALS = True




CORS_ALLOWED_ORIGINS = True

CORS_ALLOWED_ORIGINS = [ "exp://192.168.100.100:8081" , "https://5jihdge-anonymous-8081.exp.direct", "http://localhost:3000", "http://localhost:8000", "http://localhost:8081", "http://192.168.100.100:8000", ]

# token expiry management
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),   # Access token valid for 15 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # Refresh token valid for 7 days
    'ROTATE_REFRESH_TOKENS': True,                   # optional, refresh token rotation
    'BLACKLIST_AFTER_ROTATION': True,                # optional, blacklist old tokens
}

# settings.py
import os

HMAC_SECRET = os.getenv("HMAC_SECRET", "change_me_very_secret")
BATCH_SALT = os.getenv("BATCH_SALT", "change_me_salt")
# web3 settings (optional)
WEB3_PROVIDER = os.getenv("WEB3_PROVIDER", "")
CONTRACT_ADDRESS = os.getenv("CONTRACT_ADDRESS", "")
CONTRACT_ABI_PATH = os.getenv("CONTRACT_ABI_PATH", "")  # e.g., /path/to/MedicineChain_abi.json
PRIVATE_KEY = os.getenv("PRIVATE_KEY", "")
ACCOUNT_ADDRESS = os.getenv("ACCOUNT_ADDRESS", "")

# settings.py
import os


# Optional: path to system (server) private key (for signing blocks)
SYSTEM_PRIVATE_KEY_PATH = os.environ.get("SYSTEM_PRIVATE_KEY_PATH", "/etc/keys/system_priv.pem")



# REQUIRED - store securely in env / KMS in production
SERVER_PRIVATE_KEY_PEM = os.environ.get("SERVER_PRIVATE_KEY_PEM")  # PEM encoded ECDSA private key (server)
SERVER_PUBLIC_KEY_PEM = os.environ.get("SERVER_PUBLIC_KEY_PEM")    # PEM encoded server public key (optional)
BATCH_SALT = os.environ.get("BATCH_SALT", "change_this_salt")
HMAC_SECRET = os.environ.get("HMAC_SECRET", "change_me_for_dev")

# Security for dev only: in prod, use KMS and don't commit keys

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
SITE_URL = "http://192.168.100.100:8000"

BASE_URL = "http://192.168.100.100:8000"

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]