# Generated by Django 5.2.6 on 2025-12-28 11:34

import django.db.models.deletion
import django.utils.timezone
import medicine.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('remaining_quantity', models.PositiveIntegerField(default=0, help_text='Remaining units with current holder')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=medicine.models.qr_upload_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_holder', models.ForeignKey(blank=True, help_text='User who currently holds this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holding_batches', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tx_id', models.CharField(blank=True, help_text='Blockchain transaction ID', max_length=100, null=True, unique=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='medicine.medicinebatch')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DRAP_ADMIN', 'DRAP Admin'), ('MANUFACTURER', 'Manufacturer'), ('DISTRIBUTOR', 'Distributor'), ('WAREHOUSE', 'Warehouse'), ('WHOLESALER', 'Wholesaler'), ('SHOPKEEPER', 'Shopkeeper'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
