# Generated by Django 5.2.6 on 2025-12-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrecord',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
