# Generated by Django 5.2.6 on 2026-01-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_transferrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecord',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('IN_TRANSIT', 'In Transit'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferrecord',
            name='tx_id',
            field=models.CharField(blank=True, default=1, max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
