# Generated by Django 5.2.6 on 2026-01-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_alter_transferrecord_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('SOLD', 'Sold')], default='CREATED', max_length=20),
        ),
    ]
