# Generated by Django 5.2.6 on 2026-01-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_alter_transferrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinebatch',
            name='batch_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Exhausted'), ('EXPIRED', 'Expired'), ('RECALLED', 'Recalled')], default='ACTIVE', help_text='Current status of batch', max_length=20),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='total_distributed',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity distributed from manufacturer'),
        ),
    ]
