# Generated by Django 5.2.6 on 2026-01-11 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_medicinebatch_batch_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinebatch',
            name='batch_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Exhausted'), ('EXPIRED', 'Expired'), ('RECALLED', 'Recalled')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holding_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='total_distributed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SuspiciousMedicineReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=255)),
                ('reason', models.CharField(max_length=500)),
                ('reporter_name', models.CharField(max_length=255)),
                ('reporter_phone', models.CharField(max_length=50)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('INVESTIGATING', 'Under Investigation'), ('VERIFIED', 'Verified Counterfeit'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch_id'], name='medicine_su_batch_i_4f53e9_idx'), models.Index(fields=['status'], name='medicine_su_status_e20986_idx'), models.Index(fields=['-created_at'], name='medicine_su_created_0a4c5b_idx')],
            },
        ),
    ]
