# Generated by Django 5.2.5 on 2025-10-16 20:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(db_index=True, help_text='Block position in the chain')),
                ('batch_id', models.CharField(db_index=True, help_text='Medicine batch identifier', max_length=128)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Block creation timestamp')),
                ('previous_hash', models.CharField(blank=True, help_text='SHA-256 of previous block', max_length=128, null=True)),
                ('transaction_data', models.JSONField(help_text='Transaction JSON (sender, receiver, qty, notes, tx_id etc.)')),
                ('hash', models.CharField(editable=False, help_text='SHA-256 hash of this block', max_length=128)),
                ('server_signature', models.CharField(editable=False, help_text='HMAC signature for the block', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blockchain Block',
                'verbose_name_plural': 'Blockchain Blocks',
                'ordering': ('batch_id', 'index'),
                'indexes': [models.Index(fields=['batch_id', 'index'], name='blockchain__batch_i_d89fd5_idx')],
                'unique_together': {('batch_id', 'index')},
            },
        ),
    ]
