# Generated by Django 5.2.5 on 2025-10-18 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainblock',
            name='hash',
            field=models.CharField(editable=False, help_text='SHA256 hash of this block', max_length=128),
        ),
        migrations.AlterField(
            model_name='blockchainblock',
            name='index',
            field=models.PositiveIntegerField(db_index=True, help_text='Block number in the chain'),
        ),
        migrations.AlterField(
            model_name='blockchainblock',
            name='previous_hash',
            field=models.CharField(blank=True, help_text='Previous block hash', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='blockchainblock',
            name='server_signature',
            field=models.CharField(editable=False, help_text='HMAC signature for this block', max_length=256),
        ),
        migrations.AlterField(
            model_name='blockchainblock',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Block creation time'),
        ),
        migrations.AlterField(
            model_name='blockchainblock',
            name='transaction_data',
            field=models.JSONField(help_text='Transaction data (sender, receiver, etc.)'),
        ),
    ]
